### ISSUE TITLE
PDF Report Multiple Changes

### ISSUE THREAD

**Issue by appukuttan-shailesh** [HumanBrainProject/hbp-validation-client#9]
- [ ] The PDF report currently saves inside the current directory. This is ok when running the tests locally, but not ideal if run inside Collab. We should first check if it is being run inside of a Collab, and if so the report should instead (or also) be saved inside Collab storage.

- [x] Provide option for a concise pdf report without all the 'gory' details

- [ ] PDF report generation currently has problems if output files have same base name (e.g. same basename with .txt and .json)

- [x] Ensure text is not clipped when exceeding page width

- [x] When run inside Collab, should not require HBP username/password

- [x] Delete temp files and merge with final report when result does not have associated output files.

**Comment by pedroernesto** [comment]
I have followed your code in 'utils.py' of the VF to locally generate a report for FSI-cells in Basal Ganglia. Some changes may be added:

-  Line 510:  _txt_pdf.ln(3)_ instead of _txt_pdf.ln(5)_ for some long json files to fit in one page. Sometimes a page contains just a curly bracket.

- Line 497: I woul use _sorted(file_list)_ in case _file_list_ is not a sorted list of file names. That was the case in my code where I used _os.listdir(..)_ to have _file_list_. Otherwise, the order of results in the report for each cell is different, since file names order is different in each cell directory.

- the same for the cell directory names, to easy the location of each cell in the report.

**Comment by appukuttan-shailesh** [comment]
Temp files not deleted and final report not merged when result does not have associated output files.

**Comment by appukuttan-shailesh** [comment]
Implemented (in https://github.com/HumanBrainProject/hbp-validation-client/pull/65) from scratch a new report generator. Produces HTML as well as PDF.

Will be extended to display result related files once https://github.com/HumanBrainProject/hbp-validation-framework/issues/256 is resolved.

**Comment by appukuttan-shailesh** [comment]
This can be closed now as the new report generator is functional. Any bugs with the new feature can be reported afresh as it is a separate implementation.
